# Generated by Django 4.2.17 on 2026-07-12 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partenaires', '0001_initial'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('date_vente', models.DateField()),
                ('numero_bon', models.CharField(max_length=50, unique=True, verbose_name='N° du bon')),
                ('numero_facture', models.CharField(blank=True, max_length=30, unique=True)),
                ('photo_bon', models.ImageField(blank=True, null=True, upload_to='bons_vente/%Y/%m/', verbose_name='Photo du bon de pesée')),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partenaires.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_creees', to=settings.AUTH_USER_MODEL)),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matieres.materiau')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaiementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('mixte', 'Mixte (Espèces + Chèque)')], max_length=10)),
                ('montant_especes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_paiement', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.vente')),
            ],
            options={
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChequeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='N° chèque')),
                ('banque', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_encaissement', models.DateField(verbose_name="Date d'encaissement prévue")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cheques_vente/%Y/%m/')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('encaisse', 'Encaissé')], default='attente', max_length=10)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='ventes.paiementvente')),
            ],
            options={
                'ordering': ['date_encaissement'],
            },
        ),
    ]
