# Generated by Django 4.2.17 on 2026-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequevente',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('encaisse', 'Encaissé'), ('annule', 'Annulé')], default='attente', max_length=10),
        ),
    ]
